---
# Play 1: Build & export image LOCALLY (on the control machine)
- name: Build SPA image locally and export tarball
  hosts: localhost
  vars:
    image_name: "lp-app"
    image_tag: "latest"
    dockerfile_path: "app/deployment/Dockerfile"
    build_context: "app"
    tarball: "app-image.tar.gz"
  tasks:
    - name: Build SPA image for linux/amd64 and load into local engine
      ansible.builtin.command: >
        docker buildx build
        --platform linux/amd64
        --no-cache
        -t {{ image_name }}:{{ image_tag }}
        -f {{ dockerfile_path }}
        {{ build_context }}

    - name: Save image to tar.gz
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        archive_path: "{{ tarball }}"
        source: local
      register: saved_img

    - name: Show saved tarball info
      debug:
        msg: "Saved {{ image_name }}:{{ image_tag }} to {{ tarball }}"

# Play 2: Upload to VM, load, and compose up
- name: Upload image to VM and run docker-compose
  hosts: app
  become: true
  vars:
    app_dir: /opt/myapp
    tarball: app-image.tar.gz
    image_name: "lp-app"
    image_tag: "latest"
  tasks:
    #    - name: Ensure base packages (Docker + compose plugin)
    #      package:
    #        name: "{{ item }}"
    #        state: present
    #      loop:
    #        - docker.io                # Debian/Ubuntu name; use 'docker' on RHEL-like
    #        - docker-compose-plugin

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: "0755"

    - name: Copy docker-compose
      copy:
        src: "{{ item.src }}"
        dest: "{{ app_dir }}/{{ item.dest }}"
        mode: "0644"
      loop:
        - { src: "docker-compose.yaml",       dest: "docker-compose.yaml" }

    - name: Upload SPA image tarball
      copy:
        src: "{{ tarball }}"
        dest: "{{ app_dir }}/{{ tarball }}"
        mode: "0644"

    - name: Load SPA image into Docker
      community.docker.docker_image:
        load_path: "{{ app_dir }}/{{ tarball }}"
        name: "{{ image_name }}:{{ image_tag }}"
        source: load

    - name: Bring up stack and always recreate containers
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        pull: missing
        recreate: always
        state: present

    - name: Show running containers
      command: docker ps --format '{{"{{.Names}}"}} -> {{"{{.Image}}"}}'
      register: ps
      changed_when: false

    - debug:
        var: ps.stdout_lines